# Generated by Django 5.2 on 2025-04-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True, verbose_name='Title of image')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/%d/', verbose_name='Image for banner')),
            ],
        ),
        migrations.CreateModel(
            name='Iam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('photo_small', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo for profile')),
                ('photo_banner', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo for banner')),
                ('edit_at', models.DateTimeField(auto_now=True, verbose_name='Edit at')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Name of SN')),
                ('social', models.URLField(max_length=100, null=True, verbose_name='Link of any social network')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image')),
                ('link_project', models.URLField(max_length=100, null=True, verbose_name='Link project')),
            ],
        ),
    ]
