# Generated by Django 5.2 on 2025-04-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='link_project',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Link project'),
        ),
    ]
