# Generated by Django 5.2 on 2025-04-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_work_link_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Title of image'),
        ),
        migrations.AlterField(
            model_name='links',
            name='social',
            field=models.URLField(default=1, max_length=100, verbose_name='Link of any social network'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
