# Generated by Django 5.2 on 2025-05-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_carousel_title_alter_links_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, default='No title', max_length=20, null=True, verbose_name='Title of image'),
        ),
    ]
