# Generated by Django 5.2 on 2025-05-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_carousel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, default='defaults/project_image.png', upload_to='', verbose_name='Image'),
        ),
    ]
